


FROM scratch

LABEL maintainer = "adevur (madavurro@protonmail.com)"

ADD centos-8-adevur0-ppc64le.tar.xz /

RUN yum clean all && yum update -y && yum autoremove -y && yum clean all

CMD ["/bin/bash"]



